import {
  Apple,
  Bike,
  Bird,
  Book,
  Car,
  Cat,
  Clapperboard,
  Clock,
  CupSoda,
  Dog,
  Fish,
  Flower2,
  Glasses,
  Guitar,
  House,
  Key,
  Landmark,
  Moon,
  Mountain,
  Palette,
  Radio,
  Ship,
  Sun,
  TrainFront,
  TreeDeciduous,
  Trophy,
  Umbrella,
  Volleyball,
  type LucideIcon,
} from 'lucide-react';
import type { PictureId } from '@/lib/data/game-content';

/**
 * The presentational half of the game content: how a picture is actually drawn.
 * Everything is a local icon — no remote image — so the activities keep working
 * with no network at all.
 */
export const PICTURE_ICON: Record<PictureId, LucideIcon> = {
  apple: Apple,
  flower: Flower2,
  sun: Sun,
  house: House,
  car: Car,
  cat: Cat,
  bird: Bird,
  fish: Fish,
  tree: TreeDeciduous,
  umbrella: Umbrella,
  key: Key,
  book: Book,
  clock: Clock,
  cup: CupSoda,
  dog: Dog,
  guitar: Guitar,
  radio: Radio,
  film: Clapperboard,
  ball: Volleyball,
  trophy: Trophy,
  bicycle: Bike,
  train: TrainFront,
  temple: Landmark,
  mountain: Mountain,
  boat: Ship,
  palette: Palette,
  glasses: Glasses,
  moon: Moon,
};
